added static content and routes for landing page and terms/conditions…
helpinghands2/helping_hands pull request #30
Opened 2020-12-10 00:12 UTC by neilvarunnaidu

… of usage

prescribes regulations that all users will abide by, and explains the scenarios in which the user can lose access to the platform

2020-12-10 01:02 UTC, SonaliChavan95 commented on routes/index.js
> -      .render('static/about', { title: 'About', layout: 'main.handlebars' });
@neilvarunnaidu Please add layout here

2020-12-10 01:03 UTC, abhinav098 requested changes

2020-12-10 01:03 UTC, abhinav098 commented on views/static/home.handlebars
> +            <a href="/auth/signup" class="btn btn-outline-secondary">Sign up to Start Helping</a>
Please rebase your branch with master @neilvarunnaidu 

cc- @SonaliChavan95

2020-12-10 01:03 UTC, abhinav098 commented on views/static/home.handlebars
>        </div>
same comment as above.

2020-12-10 01:03 UTC, abhinav098 commented on routes/index.js
> +    res.status(200).render('static/aboutUs', { title: 'About Helping Hands' });
Please rebase your branch.

2020-12-10 01:03 UTC, SonaliChavan95 commented on routes/index.js
> -      .render('static/about', { title: 'About', layout: 'main.handlebars' });
you also need to rebase your branch with master. Let me know in case you need help

2020-12-10 01:05 UTC, SonaliChavan95 commented on views/static/home.handlebars
> -            <a href="/auth/signup?uType=Recipient" class="btn btn-outline-success">Sign Up & Receive</a>
@neilvarunnaidu Here, param is removed in the URL. Please check your changes and add back the missing code.

2020-12-10 01:06 UTC, abhinav098 commented on routes/index.js
> +    res.status(200).render('static/aboutUs', { title: 'About Helping Hands' });
Please don't omit the layout parameter, it's important.

2020-12-10 01:07 UTC, abhinav098 commented on views/static/home.handlebars
> +            <a href="/auth/signup" class="btn btn-outline-secondary">Sign up to Start Helping</a>
`/auth/signup?uType=Donor` for donor signup and `/auth/signup?uType=Recipient` for recipient sign up.

2020-12-10 01:08 UTC, abhinav098 commented on views/static/home.handlebars
> +            <a href="/auth/signup" class="btn btn-outline-secondary">Sign up to Start Helping</a>
Please make this fix wherever you are using signup even on other pages. @neilvarunnaidu

2020-12-10 01:12 UTC, abhinav098 requested changes

2020-12-10 01:12 UTC, abhinav098 commented on views/static/home.handlebars
> +        <h1 class="text-success">Helping each other has never been more convenient</h1>
class should be `text-blue` it's linked to css.

2020-12-10 01:12 UTC, abhinav098 commented on views/static/home.handlebars
> -      </div>
Please add this code back. It's for the recent donations feature.

2020-12-10 03:27 UTC, abhinav098 commented on views/static/aboutUs.handlebars
> +      <a href="/auth/signup" class="btn btn-outline-success">Watch us in action</a>
use correct URL.

2020-12-11 00:06 UTC, abhinav098 requested changes

2020-12-11 00:06 UTC, abhinav098 commented on routes/index.js
>    });
Fix this layout to 

`layout: req.session.user ? 'main2' : 'main',`

2020-12-11 00:06 UTC, abhinav098 commented on routes/index.js
> +      layout: 'main'
`layout: req.session.user ? 'main2' : 'main',`

2020-12-11 00:16 UTC, abhinav098 commented on views/static/home.handlebars
> +              <br>
```suggestion
```

2020-12-11 00:16 UTC, SonaliChavan95 approved these changes

2020-12-11 00:31 UTC, abhinav098 approved these changes

2020-12-11 00:31 UTC, merged