Landing page
helpinghands2/helping_hands pull request #5
Opened 2020-11-15 15:25 UTC by iamikenna

Please review

2020-11-16 16:00 UTC, abhinav098 requested changes
@iamikenna , nice work, I have added some comments on your PR. 

Please take a look at those, and let me know in case you face any problems.

2020-11-16 16:05 UTC, SonaliChavan95 requested changes

2020-11-16 16:05 UTC, SonaliChavan95 commented on package-lock.json
> +{
@iamikenna You can remove this file from this PR. 

You can also you .gitignore for ignoring this file while making a commit. 
https://docs.github.com/en/free-pro-team@latest/github/using-git/ignoring-files

2020-11-16 16:08 UTC, abhinav098 requested changes

2020-11-16 16:08 UTC, abhinav098 commented on routes/home.js
> +        res.status(404).send(e)
Use this file for error rendering. We'll style that error page later.
`https://github.com/SonaliChavan95/DonationBank/blob/master/views/customError.handlebars`

2020-11-16 16:08 UTC, abhinav098 commented on views/posts/home.handlebars
> +
something like this

```.login-info {
  margin-top: 6em;
}

.info-text {
  margin-top: 7em;
}
```

2020-11-16 16:08 UTC, abhinav098 commented on views/posts/home.handlebars
> +                <h4>For Donnors</h4>
Typo `Donors`

2020-11-16 16:08 UTC, abhinav098 commented on views/posts/home.handlebars
> +        <h1>Matching Donnors with Needy people in the Society</h1>
Typo, `Donors`

2020-11-16 16:09 UTC, abhinav098 commented
@iamikenna , there are some conflicts in the PR. Please resolve them as well.

2020-11-16 16:16 UTC, abhinav098 commented on app.js
> +});
You guys can ignore settings for vue, ruby, theme, and font. 

Rest all are really useful. I would recommend everyone uses it.
@neilvarunnaidu @SonaliChavan95 @iamikenna

2020-11-16 23:48 UTC, SonaliChavan95 commented on views/posts/home.handlebars
> +      <img src="hands.jpg" alt="" id="b_w_hands">
we need to add some data in `alt` attribute here. Also @iamikenna can you please add some fixed height to this image? Without height, image might look very big on some screen.

2020-11-17 15:55 UTC, SonaliChavan95 commented on package-lock.json
> +{
@iamikenna this should get fixed in this PR https://github.com/helpinghands2/helping_hands/pull/7. 
You can ignore the comment.

2020-11-17 16:03 UTC, iamikenna commented on public/js/script.js
> +        }
Yes mistake

2020-11-17 16:04 UTC, iamikenna commented on routes/home.js
> +        res.status(404).send(e)
Static or not, does the same job

2020-11-17 16:07 UTC, iamikenna commented on app.js
> +});
Changing my editor settings changes a-lot in my other projects

2020-11-17 16:15 UTC, iamikenna commented on public/js/script.js
> +        }
yes

2020-11-17 16:15 UTC, iamikenna commented on views/posts/home.handlebars
> +
copy that

2020-11-18 04:51 UTC, merged